sudo: required
dist: xenial

services:
- docker

install: scripts/setup-tools-for-ubuntu.sh

# Add charts to build here.
env:
- CHART_TO_BUILD=enterprise-suite

jobs:
  include:
  - stage: test
    name: "Quick Tests"
    script: make test CHART=$CHART_TO_BUILD

  - name: "Minikube Tests"
    install:
    - scripts/setup-tools-for-ubuntu.sh
    - scripts/setup-minikube-for-linux.sh
    script: make minikube-test CHART=$CHART_TO_BUILD
    if: env(CHART_TO_BUILD) = enterprise-suite

  - stage: release
    script: make release CHART=$CHART_TO_BUILD
    # Only build release if we're on master and it's tagged with CHART_TO_BUILD, e.g. enterprise-suite-0.0.18.
    if: (branch = master) AND (tag =~ concat(^,env(CHART),-.*)

notifications:
  email: false
  slack:
    secure: Wbp33+rhtKSkDQsoBq33b3/WFk7/vzoKNqVoGhjFyXtBTE/mP/C7ZvGDxSWVLhbKTqCzlXpp3BlO9/g2PJa3GafssYr+ZRxYzkyXqQnjIUTFylSqKZky729LTtE8eBfreyjX1JZgVu0++kQTkUsQCjBEW0dhZsVSnd8QAQwQQigxue9/wPiZABOuoaZ4UCPoE7EzhRH86MO3RhRdfIMSOwj94cPf95NtN292jmOEsTCayc+CVfJ77wbbANAvqX2kBaBQTgREUk/0guR8bVTO8YxExuYkNEeQZRKa8TLjP9A3Gkd/JED6R3FLLw7EcT9J62zWLTKZqRKCb+Nhc01uy67/m21bVlHfphPgNAy3rU27lmVqzS0NCyiqix8uenoewjFYYbR8+3nTO+kuqeP/lRUmmINkzornICtx+POP+mGOSE4llmplZIhJKWBN1x/OtY9XvIXd1WcZtWnk310zurCN+0qjBIewjs4a28ZcZdB8e/si+Cx5YT2UvXgYZipjM3CX29AaPaCGsuGdjQJN/OFzYbwiJbvfI/O9OEl32aMfu1w4P3WtLNVT2eW6Kdu0HJaRKvtSwzKBmYP8b5xdTQemsG2R97rPN1uTOwVWwviOQgg/pycIxjNawMf6s+5I7CK3zO3QjwrfWSq7d8Nm2qC5J+82+rQSZ6YDr3wJliI=
